site_name: CDISC Biomedical Concepts
site_url: https://cdisc-org.github.io/COSMoS/
nav:
    - Home: index.md
    #- About: about.md
plugins:
    - search
    - mermaid2:
        arguments:
          startOnLoad: false
          mermaid:
              er:
                  useMaxWidth: true
markdown_extensions:
    - markdown.extensions.md_in_html
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid_custom

docs_dir: project/docs
site_dir: docs