openapi: 3.0.0
info:
  title: CDISC Conceptual and Operational Standards Metadata (COSMoS)
  description: REST API documentation for COSMoS
  version: '0.1'
  contact:
    name: CDISC Library Support
    email: cdisc_library_support@cdisc.org
  license:
    name: License for CDISC Members & Open Source Developers
    url: https://www.cdisc.org/cdisc-library/api-account-request
externalDocs:
  description: Media Type Support Matrix
  url: https://wiki.cdisc.org/display/LIBSUPRT/Media+Type+Support+Matrix
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/CDISC1/cdisc-library/1.5
  - description: Production CDISC Libray
    url: https://library.cdisc.org/api
security:
  - ApiKeyAuth: []
paths:
  /mdr/cosmos/biomedicalconcepts:
    get:
      operationId: api.cosmos.get_biomedicalconcepts
      summary: Get Biomedical Concept List
      tags:
        - COSMoS
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cosmosBiomedicalConcepts'
        '400':
          $ref: '#/components/responses/statusBadRequest'
        '401':
          $ref: '#/components/responses/statusUnauthorized'
        '403':
          $ref: '#/components/responses/statusForbidden'
        '404':
          $ref: '#/components/responses/statusNotFound'
        '405':
          $ref: '#/components/responses/statusNotAllowed'
        '406':
          $ref: '#/components/responses/statusNotAcceptable'
        '500':
          $ref: '#/components/responses/statusInternalError'
        '503':
          $ref: '#/components/responses/statusServiceUnavailable'
        '504':
          $ref: '#/components/responses/statusGatewayTimeout'

  /mdr/cosmos/biomedicalconcepts/{concept}:
    get:
      operationId: api.cosmos.get_biomedicalconcept
      summary: Get Biomedical Concept
      tags:
        - COSMoS
      parameters:
        - $ref: '#/components/parameters/concept'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cosmosBiomedicalConcept'
        '400':
          $ref: '#/components/responses/statusBadRequest'
        '401':
          $ref: '#/components/responses/statusUnauthorized'
        '403':
          $ref: '#/components/responses/statusForbidden'
        '404':
          $ref: '#/components/responses/statusNotFound'
        '405':
          $ref: '#/components/responses/statusNotAllowed'
        '406':
          $ref: '#/components/responses/statusNotAcceptable'
        '500':
          $ref: '#/components/responses/statusInternalError'
        '503':
          $ref: '#/components/responses/statusServiceUnavailable'
        '504':
          $ref: '#/components/responses/statusGatewayTimeout'

  /mdr/cosmos/biomedicalconcepts/{concept}/dataelementconcepts:
    get:
      operationId: api.cosmos.get_dataelementconcepts
      summary: Get Biomedical Concept Data Element Concepts List
      tags:
        - COSMoS
      parameters:
        - $ref: '#/components/parameters/concept'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cosmosDataElementConcepts'
        '400':
          $ref: '#/components/responses/statusBadRequest'
        '401':
          $ref: '#/components/responses/statusUnauthorized'
        '403':
          $ref: '#/components/responses/statusForbidden'
        '404':
          $ref: '#/components/responses/statusNotFound'
        '405':
          $ref: '#/components/responses/statusNotAllowed'
        '406':
          $ref: '#/components/responses/statusNotAcceptable'
        '500':
          $ref: '#/components/responses/statusInternalError'
        '503':
          $ref: '#/components/responses/statusServiceUnavailable'
        '504':
          $ref: '#/components/responses/statusGatewayTimeout'

  /mdr/cosmos/biomedicalconcepts/{concept}/dataelementconcepts/{dataelementconcept}:
    get:
      operationId: api.cosmos.get_dataelementconcept
      summary: Get Data Element Concepts
      tags:
        - COSMoS
      parameters:
        - $ref: '#/components/parameters/concept'
        - $ref: '#/components/parameters/dataelementconcept'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cosmosDataElementConcept'
        '400':
          $ref: '#/components/responses/statusBadRequest'
        '401':
          $ref: '#/components/responses/statusUnauthorized'
        '403':
          $ref: '#/components/responses/statusForbidden'
        '404':
          $ref: '#/components/responses/statusNotFound'
        '405':
          $ref: '#/components/responses/statusNotAllowed'
        '406':
          $ref: '#/components/responses/statusNotAcceptable'
        '500':
          $ref: '#/components/responses/statusInternalError'
        '503':
          $ref: '#/components/responses/statusServiceUnavailable'
        '504':
          $ref: '#/components/responses/statusGatewayTimeout'

components:

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: api-key

  parameters:
    concept:
      in: path
      name: concept
      required: true
      description: COSMoS Biomedical Concept
      schema:
        type: string
        example: C49676
    dataelementconcept:
      in: path
      name: dataelementconcept
      required: true
      description: Data Element Concept
      schema:
        type: string
        example: C73688

  responses:
    statusBadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'
    statusForbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'
    statusUnauthorized:
      description: Unauthorized
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'
    statusNotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'
    statusNotAllowed:
      description: Method Not Allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'
    statusNotAcceptable:
      description: Not Acceptable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'
    statusInternalError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'
    statusServiceUnavailable:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'
    statusGatewayTimeout:
      description: Gateway Timeout Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultErrorResponse'

  schemas:
    defaultErrorResponse:
      properties:
        statusCode:
          description: HTTP Status Code
          type: string
        detail:
          description: Detail
          type: string
        message:
          description: Message
          type: string
    link:
      description: Resource Reference
      properties:
        href:
          description: href
          type: string
          format: uri
        title:
          description: title
          type: string
        type:
          description: type
          type: string

    cosmosBiomedicalConcepts:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/cosmosBiomedicalConceptsLinks'
    
    cosmosBiomedicalConceptsLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/cosmosBiomedicalConceptsRef'
        biomedicalConcepts:
          type: array
          items:
            $ref: '#/components/schemas/cosmosBiomedicalConceptRef'
    cosmosBiomedicalConceptsRef:
      description: Biomedical Concepts Reference
      type: object
      allOf:
        - $ref: '#/components/schemas/link'

    cosmosBiomedicalConcept:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/cosmosBiomedicalConceptLinks'
        id:
          type: string
          example: C49676
        href:
          type: string
          format: uri
          example: https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=22.03d&ns=ncit&code=C49676
        category:
          type: array
          items:
            type: string
          example: 
            - Vital Signs
        shortName:
          type: string
          example: Pulse Rate
        synonym:
          type: array
          items:
            type: string
          example:
            - Pulse
        resultScale:
          type: string
          enum:
            - Quantitative
            - Ordinal
            - Nominal
            - Narrative
          example: Quantitative
        definition:
          type: string
          example: >-
            The rate of the pulse as observed in an artery, expressed as beats per
            minute. It can be measured at several anatomic sites, including the wrist,
            neck, temple, groin, behind the knees, or on top of the foot.
        coding:
          type: array
          items:
            $ref: '#/components/schemas/cosmosBiomedicalConceptCoding'
        dataElementConcepts:
          type: array
          items:
            $ref: '#/components/schemas/cosmosDataElementConcept'
      required:
        - id
        - category
        - shortName
        - definition

    cosmosBiomedicalConceptCoding:
      type: object
      properties:
        code:
          type: string
          example: 39156-5
        system:
          type: string
          example: http://loinc.org/
        systemName:
          type: string
          example: LOINC
      required:
        - code
        - system

    cosmosBiomedicalConceptLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/cosmosBiomedicalConceptRef'
        parentBiomedicalConcept:
          $ref: '#/components/schemas/cosmosBiomedicalConceptParentRef'

    cosmosBiomedicalConceptRef:
      description: Biomedical Concept Reference
      type: object
      allOf:
        - $ref: '#/components/schemas/link'

    cosmosBiomedicalConceptParentRef:
      description: Biomedical Concept Parent Reference
      type: object
      allOf:
        - $ref: '#/components/schemas/link'


    cosmosDataElementConcepts:
      type: object
      properties:
        id:
          type: string
          example: C49676
        href:
          type: string
          format: uri
          example: https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=22.03d&ns=ncit&code=C49676
        category:
          type: array
          items:
            type: string
          example: 
            - Vital Signs
        shortName:
          type: string
          example: Pulse Rate
        synonym:
          type: array
          items:
            type: string
          example:
            - Pulse
        resultScale:
          type: string
          enum:
            - Quantitative
            - Ordinal
            - Nominal
            - Narrative
          example: Quantitative
        definition:
          type: string
          example: >-
            The rate of the pulse as observed in an artery, expressed as beats per
            minute. It can be measured at several anatomic sites, including the wrist,
            neck, temple, groin, behind the knees, or on top of the foot.
        coding:
          type: array
          items:
            $ref: '#/components/schemas/cosmosBiomedicalConceptCoding'
        _links:
          $ref: '#/components/schemas/cosmosDataElementConceptsLinks'
    
    cosmosDataElementConceptsLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/cosmosDataElementConceptsRef'
        biomedicalConcept:
          $ref: '#/components/schemas/cosmosBiomedicalConceptRef'
        dataElementConcepts:
          type: array
          items:
            $ref: '#/components/schemas/cosmosDataElementConceptRef'
    cosmosDataElementConceptsRef:
      description: Data Element Concepts Reference
      type: object
      allOf:
        - $ref: '#/components/schemas/link'

    cosmosDataElementConcept:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/cosmosDataElementConceptLinks'
        href:
          type: string
          format: uri
          example: https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=22.03d&ns=ncit&code=C73688
        label: 
          type: string
          example: Count per Minute
        dataType:
          type: string
          example: integer
        exampleSets:
          type: array
          items:
            type: string
          example:
            - Beats per Minute
        
    cosmosDataElementConceptLinks:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/cosmosDataElementConceptRef'
        Concept:
          $ref: '#/components/schemas/cosmosBiomedicalConceptRef'

    cosmosDataElementConceptRef:
      description: Data Element Concept Reference
      type: object
      allOf:
        - $ref: '#/components/schemas/link'

